---
- name: all tasks
  hosts: all
  vars:
    homeuser: clizby
  tasks:
     - name: copy aliases dotfile to user
       copy:
         src: .aliases
         dest: /home/{{ homeuser }}/.aliases
         owner: "{{ homeuser }}"
         group: "{{ homeuser }}"
         mode: 0644
     - name: add .aliases to .bashrc
       lineinfile:
         path: /home/{{ homeuser }}/.bashrc
         line: 'source ~/.aliases'
     - name: remove .emacs file
       ansible.builtin.file:
         path: /home/{{ homeuser }}/.emacs
         state: absent
     - name: Create emacs.d directory
       ansible.builtin.file:
        path: /home/{{ homeuser }}/.emacs.d
        state: directory
        mode: '0755'
        owner: "{{ homeuser }}"
     - name: copy init.el to .emacs.d directory
       copy:
         src: init.el
         dest: /home/{{ homeuser }}/.emacs.d
         owner: "{{ homeuser }}"
         group: "{{ homeuser }}"
         mode: 0644
     - name: install packages
       package:
         name: "{{ packages }}"
       vars:
         packages:
         - debsecan
         - emacs
         - audacious
         - audacious-plugins
         - mpv
         - vlc
         - neovim
         - podman
         - pandoc
         - remmina-plugin-rdp
         - remmina
         - pavucontrol
         - httpie
         - nextcloud-desktop
         - build-essential
         - libdrm-dev
         - make
         - dkms
         - ripgrep
         - clang
         - zsh
         - golang
         - gopls
         - flatpak
         - qemu-system-x86
         - libvirt-daemon-system
         - libvirt-clients
         - virt-manager
         - gir1.2-spiceclientgtk-3.0
         - dnsmasq
         - qemu-utils  
         - apt-listbugs
         - apt-listchanges
         - htop
         - apparmor-profiles-extra 
     - name: add flathub repo
       ansible.builtin.shell:
         cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
     - name: install flatpaks
       flatpak:
         name: "{{ flatpaks }}"
       vars:
         flatpaks:
         - org.chromium.Chromium
         - io.gitlab.librewolf-community
         - org.freedesktop.Platform.ffmpeg-full/x86_64/20.08
         - net.sourceforge.projectM
         - com.github.tchx84.Flatseal
         - org.signal.Signal
         - com.discordapp.Discord
         - im.riot.Riot
     - name: Enable libvirtd
       ansible.builtin.systemd:
         name: libvirtd.service
         state: started
         enabled: yes
     # taken from https://waylonwalker.com/install-rust/
     - name: check if cargo is installed
       shell: command -v cargo
       register: cargo_exists
       ignore_errors: yes
     - name: Download Installer
       when: cargo_exists is failed
       get_url:
         url: https://sh.rustup.rs
         dest: /tmp/sh.rustup.rs
         mode: '0755'
         force: 'yes'
       tags:
         - rust
     - name: install rust/cargo
       when: cargo_exists is failed
       shell: /tmp/sh.rustup.rs -y
       tags:
         - rust
     - name: add cargo sourcing to .zshrc
       lineinfile:
         path: /home/{{ homeuser }}/.zshrc
         line: '[ -f ~/.cargo/env ] && source $HOME/.cargo/env'
     - name: add cargo sourcing to .bashrc
       lineinfile:
         path: /home/{{ homeuser }}/.bashrc
         line: '[ -f ~/.cargo/env ] && source $HOME/.cargo/env'
 
